### ISSUE TITLE
ios: experiment with 1st default session startup

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#104]
1st session we start for "bundleId": "com.apple.springboard" corrupt a lot of logic in automation and automatic restart...
let's experiment again what we can do, maybe on stf side to skip this operation on appium container startup.

**Comment by dhreben** [comment]
@vdelendik 

Tested  1st session on STF:

**Old behavior** - appium:2.0.11
IPhone_8 plus = 4.5sec
iPhone 8 = 5.1 sec

**With removed 1st wda session startup** - appium:2.0.12-beta1.
IPhone_8 plus = 5.6 sec
iPhone 8 = 6.5 sec
