### ISSUE TITLE
reuse netcat (nc) and connection to wda mjpeg port to detect wda crash asap

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#108]
we have to organize it inside the appium code with ability to exit with non 0 error code and restart everything or initiate `/opt/start-wda.sh`. This shell script might do extra startup steps and exit if wda not started.

1st the most interesting place is driver session startup exception
2nd might be before session request? we already do it by mcloud-grid using 500ms timeout. it might be interesting to run it on backend with bigger delay to ensure we detect real failure. and if status-wda fail on backend then (take a look above).

And finally - do we need something similar from stf when we initiate new session?

**Comment by vdelendik** [comment]
updated subject as telnet utility launched in backgroud might detect wda crash asap. in comparison with wda_port connection to mjpeg_port is pretty stable and might be used to detect wda crash asap

**Comment by vdelendik** [comment]
finally refactored using netcat (nc). so test scenario should include:
1. setup and start iOS container
2. start tailing of the iOS device appium container
-> right after wda startup we should have message `Connecting to 192.168.89.19 8101 using netcat...`
3. bash into the appium container in 2nd terminal
4. kill wda application using `ios kill $WDA_BUNDLEID --udid=$DEVICE_UDID`
-> iOS device should be disconnected asap in the STF
-> in logs we should see that previos `netcat connection is closed.`  and wda is starting again asap:
```
netcat connection is closed.
[01/05/2022 03:15:36] Killing existing WebDriverAgent application if any
{"level":"error","msg":"process of com.facebook.WebDriverAgentRunner.xctrunner not found","time":"2022-05-01T03:15:36-07:00"}
[01/05/2022 03:15:36] Starting WebDriverAgent application on port 8100
detecting WDA_HOST ip address...
attempt 1
```

**Comment by dhreben** [comment]
Verified.
