### ISSUE TITLE
ios: do extra verification on usbmuxd service status

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#117]
locale connect shell script should 1st of all verify usbmuxd service status and wait until it is up&running...
only after that we have to verify via `ios list`...

Also it has sense to move local and wireless connect into the one place in the beginning of entry point and do `exit 1` everytime at the end.

**Comment by vdelendik** [comment]
as there is no way to detect usbmuxd service status inside container I just increased pause for default `ios list | grep -c udid` verification upto 50s by default.
Testing scenario should include verification that described steps are applied for the mcloud server: https://github.com/zebrunner/mcloud-agent/issues/128 and

1. after killing usbmuxd process all connected iOS devices reconnected automatically
```
sudo pkill usbmuxd
-> all iOS containers should be disconnected in STF asap
docker ps -a 
-> all iOS containers recreated and in starting state. double check that CREATED is seconds and not minutes or hours
```
-> open started iOS device successfully in STF and do any action

2. do usbmuxd service restart
```
sudo service usbmuxd restart
-> all iOS containers should be disconnected in STF asap
docker ps -a 
-> all iOS containers recreated and in starting state. double check that CREATED is seconds and not minutes or hours
```
-> open started iOS device successfully in STF and do any action

3. do server reboot `sudo reboot now`
-> all iOS devices restarted automatically and fully operational in STF

**Comment by dhreben** [comment]
All steps verified as well `power off` server
