### ISSUE TITLE
killed appium by reboot is not restarted automatically

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#118]
if we reboot server or restart docker service our upload function tries to capture any existing video recording and sessionId.
if not `exit 0` is returned and as result docker container not restarted automatically

**Comment by vdelendik** [comment]
fixed to test reboot the server when let's say any android test is up&running in multi-threading mode
-> after restart all android device containers are up&running and fully operational
-> verify that aborted tests have video recording and session logs uploaded into the reporting
Verify that appium docker log container where tests were running have something like:
```
[info] [UploadArtifacts] S3_KEY_PATTERN: ${S3_KEY_PATTERN}
```

**Comment by dhreben** [comment]
**Verified.**
Log from appium container:
`[info] [UploadArtifacts] S3_KEY_PATTERN s3://zebrunner.org-engine/demo/artifacts/test-sessions/d09b4..........fb741a`

As well:

After `sudo reboot` some device containers have `(unhealthy)` status with error:
```
Unhandled rejection Error: connect EHOSTUNREACH 172.18.0.19:5037
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
```
Separate ticket was created  https://github.com/zebrunner/stf/issues/444
