### ISSUE TITLE
check-wda can't use new ip address

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#125]
in case we change ip address of the iOS device our check-wda.sh continue to execute verification using old value and restart WDA constantly...

Good way to repro:
1. start everything correctly
2. disable wi-fi
3. restart iOS container `zebrunner-farm restart udid`
-> WDA tries to start using localhost which is wrong
4. enable wi-fi again
-> wda is started correctly, env file is populated with valid data but check-wda.sh continue to use localhost...

So we have to reload WDA_HOST and MJPEG_PORT at run-time before validation... 
P.S. Think about zero file size check to avoid forcibly restart during restart

**Comment by vdelendik** [comment]
done. please follow above scenario to test that new WDA_HOST ip is propagated correctly

**Comment by dhreben** [comment]
Verified.
