### ISSUE TITLE
handle unauthorized and unknown (unavailable) device state

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#128]
for now local_connect.sh return 1 for both unauthorized and not available.
fir unauthorized we should de reconnect using usbreset but for not available regular restart helps in 99%.

so let's return different values for different cases and handle them correctly

**Comment by vdelendik** [comment]
done. we have to reconnect with `exit 0` for unauthorized and `exit 1` with automatic restart for unknown not available device state

**Comment by dhreben** [comment]
Tested on MFP
Closed.
