### ISSUE TITLE
reuse dockerized usbmuxd service benefits

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#137]
https://github.com/zebrunner/mcloud-agent/issues/127
https://github.com/zebrunner/stf/issues/535
https://github.com/zebrunner/mcloud-device/issues/107

**Comment by vdelendik** [comment]
feature is available in `public.ecr.aws/zebrunner/appium:1.4.6-beta8`. setup mcloud from develop branch and test based on https://github.com/zebrunner/stf/issues/535 steps

**Comment by dhreben** [comment]
Verified.
