### ISSUE TITLE
add support of --endpoint-url for s3 uploader

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#141]
to minimize NAT expenses we can reuse vpc private link and publish artifacts using private routing:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/privatelink-interface-endpoints.html

to make it happen uploader command should be flexible which might add `--endpoint-url "https://bucket.yyy.s3.us-east-2.vpce.amazonaws.com"` when required

**Comment by vdelendik** [comment]
it should be supported now after reusing our default uploader image: https://github.com/zebrunner/uploader/releases/tag/3.1.
during the testing we have to try to use custom s3 endpoint and maybe document it

**Comment by dhreben** [comment]
Closed
