### ISSUE TITLE
reuse another location for default chrome apk installer

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#142]
we have to change /opt/zebrunner by /tmp/zebrunner to keep only browser apk to share

**Comment by vdelendik** [comment]
fixed. already applied on org. tested successfully on my own: https://vd2.zebrunner.org/projects/DEF/automation-launches/2109/tests/32724
@okamara - feel free to retest or close if you trust me)

**Comment by okamara** [comment]
Tests are failed https://react.zebrunner.org/projects/DEF/automation-launches/794/tests/6562?runsState=cGFnZT0x

**Comment by okamara** [comment]
Test with Redroid for web is failed, session is started
