### ISSUE TITLE
don't kill container in case of unhealthy adb connection

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#144]
we have to find better way to kill `node` process and restart appium device container.
as of now we do `pkill node` as part of healthcheck and it block normal execution on redroid emulator as it starts with a delay.

let's keep healtchcheck only to return status as of now and don't terminate processes as we do for iOS

**Comment by vdelendik** [comment]
fixed, 1.4.8 uploaded to AWS ECR. in scope of testing obligatory setup physical device farm using this version and try to emulate any adb related issue inside appium container aka kill adb service...

ideally - on mcloud container should be restarted somehow... if not - we should find better place for killing the process.
As an idea -> organize water for adb proces and as only it exited, exit from container....

**Comment by dhreben** [comment]
Сlosed. Opened relevant ticket https://github.com/zebrunner/appium/issues/161
