### ISSUE TITLE
ios: reuse proxy for redirecting wda requests through appium container

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#148]
Above improvement should allow to reuse iOS devices without wi-fi connection or being located in different networks.

1. we have to start port forwarding for wda port and mjpeg port
```
ios forward $WDA_PORT $WDA_PORT
ios forward $MJPEG_PORT $MJPEG_PORT
```
3. any problem with port forwarding should initiate container restart
4. investigate if wda_port inside appium container should be shared outside but ideally it would be great to keep

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/appium/pull/149/files

during the testing, please make sure to kill forward processes for both wda and mjpeg
-> after killing containers should be restarted and reanimated automatically asap
```
docker exec -ti device-iPhone-...-appium bash
ps -ef | grep forward
kill -9 <pid>
```

**Comment by dhreben** [comment]
Verified.
