### ISSUE TITLE
capture `fallbackSessionId` from carina for negative scenarios

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#15]
We added `fallbackSessionId` for every driver session request. it might be used to correlate invalid session artifacts aka video/logs and failure in the test.

High level scenario is:
1. start video recording anyway using video_#.mp4 template
2. As only new session request arrived - kill existing recording and start new one using detected sessionId
3. If all good, forget about video*.mp4 files and concat/upload sessionId*.mp4
4. If session not started or docker interrupted: collect video*mp4, sessionId*mp4 and publish using `fallbackSessionId/video.mp4`. Log is simpler because current appium log might be used

Note: `fallbackSessionId` appeared only in `7.2.14-SNAPSHOT` carina

**Comment by okamara** [comment]
According to @vdelendik changes are reverted
