### ISSUE TITLE
remove WDA_ENV and LOG generation

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#150]
as we could use efficiently port forwarding there is no sense anymore to generate and share WDA_HOST/PORT etc via WDA_ENV file.
so far in 1.4.9 we keep it as appium use it somehow.

Let's review image completely and use WDA_HOST, WDA_POST and MJPEG_PORT only from env vars inside.
And don't generate env and log.

As about wda_ip detection it should be replaced by regular `/status` healtchcheck call in cycle

**Comment by vdelendik** [comment]
done. we continue to generate wda.log but wda.env was removed and not used anymore

**Comment by dhreben** [comment]
Verified.
