### ISSUE TITLE
as we don't need wda ip anymore we can simplify startup verification

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#152]
we do smart analysis and ip detection using log parser:
https://github.com/zebrunner/appium/commit/01b78419877db6b79e4b5b0a5e0c0e16eacb5da2#diff-e20bab65472b09a5c0acf0c33982552c9f46745b1fdd23a65c76ec33cefb8c3eR28

as starting from mcloud 2.4 we don't need this ip and can commnicate with device internally we can simplify startup detection and analyze for `ServerURLHere` presence in log file.

After that we can test wda by status call to confirm it is up and waiting for requsets... After updating we can forget about parsing any wd log formats

**Comment by vdelendik** [comment]
done. we reused curl to verify wda status. all ip detection code and logs analysis was removed. moreover, added in the beginning of the script wda session detection and skip restart if everything is valid

**Comment by dhreben** [comment]
Verified.
