### ISSUE TITLE
be able to exit from container for adb failures

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#155]
we need flag to manage how to operate in case of adb offline etc. by default exit/kill should be dibled and only for real devices we have to enable it explicitly in scope of mcloud:agent: https://github.com/zebrunner/mcloud-agent/issues/162

after migrating to mcloud:2.4 as we removed kill/exit from healthcheck some android devices moved to offline and don't recover automatically...

**Comment by vdelendik** [comment]
done, testing should be organized together with https://github.com/zebrunner/mcloud-agent/issues/162.
going to release 1.4.10 as changes are pretty small

**Comment by dhreben** [comment]
Verified.
