### ISSUE TITLE
Incorrect deviceType set for devices that do not return tv for ro.build.characteristics property

### ISSUE THREAD

**Issue by fkhan2** [zebrunner/appium#157]
https://github.com/zebrunner/appium/blob/master/files/android.sh#L5 -> For devices like [Xiaomi Stick](https://www.mi.com/us/mi-tv-stick/) or [Mi Box S](https://www.mi.com/us/mi-box-s/) `adb shell getprop ro.build.characteristics` returns `default`; thus, mislabeling the device type as `phone`. This causes issues while reserving tv type devices during test runs due to capability mismatch.

**Comment by vdelendik** [comment]
verified on my own using exact tv and adb cli
