### ISSUE TITLE
integrate opencv support into the bundled appium

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#158]
we need opencv4nodejs module installed as part of appium imae to be able to support fin by image:
https://zebrunner.github.io/carina/automation/mobile/#how-to-use-find-by-image-strategy

let's produce both images, including in the tag openc key and it's version.

**Comment by vdelendik** [comment]
done. such images pushed into the aws registry:
public.ecr.aws/zebrunner/appium:1.4.11-opencv5.6.0
public.ecr.aws/zebrunner/appium:1.4.11-opencv4.16.0

full tags list is available here: https://gallery.ecr.aws/zebrunner/appium

**Comment by dhreben** [comment]
Verified. 1.4.11-opencv5.6.0 and 1.4.11-opencv4.16.0 added on zebrunner/appium
