### ISSUE TITLE
for wireless appium connection make sure to start adb server inside

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#160]
Before we run any adb commands (in the wireless connect script) we need to start adb using `adb -a -P 5037 server nodaemon`
https://github.com/zebrunner/appium/blob/master/wireless_connect.sh#L9

Without it stf can't connect to the appium->device... So far wireless devices were used as scalable emulators without STF integration. So need to adjust to finalize with such kind of connections.

**Comment by vdelendik** [comment]
reorganized a little bit local and remote connect: https://github.com/zebrunner/appium/pull/223
for both variants we will start local adb in advance using `-a` argument which allows external connection from stf etc containers

**Comment by dhreben** [comment]
Verified.
Steps:
```
docker exec -ti device-Samsung_Tab_A7-R............X2J-appium bash
root@33227c8190f6:/home/androidusr# ps -ef
root        11     1  0 15:08 pts/0    00:00:01 adb -a -P 5037 server nodaemon
```
