### ISSUE TITLE
New logic with recovery don't kill container in case of unhealthy adb connection

### ISSUE THREAD

**Issue by dhreben** [zebrunner/appium#161]
sbj
https://github.com/zebrunner/appium/issues/144

**Comment by vdelendik** [comment]
we do have `/status-adb` endpoint which is verified right before session startup. it has sense to move kill node operation onto this level. as it is part of the appium code we can do exit(1) to initiate restart

**Comment by vdelendik** [comment]
`/status-adb` is improved to support exit with error code on exit. it suppose to be integrated into the mcloud-grid to verify device before session start and exit with exact error code
https://github.com/zebrunner/appium/pull/187/files

**Comment by dhreben** [comment]
Will be check after fix https://github.com/zebrunner/mcloud-grid/issues/96
