### ISSUE TITLE
add support for non suprevised iOS devices via api

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#178]
https://github.com/danielpaulus/go-ios/tree/main/restapi
https://github.com/danielpaulus/go-ios/blob/main/restapi/api/device_endpoints.go#L322

**Comment by vdelendik** [comment]
done without go ios rest api. we were able to preserve pairing state via `/var/lib/lockdown/udid.plist` file. Also as a benefit we could remove p12 file and support operations at all.

btw, every iOS device can use:
1. global wda WDA_FILE and WDA_BUNDLEID
2. per device wda_file and wda_bundleid to override/customize global

testing scenarios - TBD

**Comment by dhreben** [comment]
Verified.

Steps:
1. First install CE+mcloud agent ->Trust/not trust field appears -> Trust-> device  is appear on STF
2. Disconnect-> Connect  device - > Trust/not trust field  is not appears - > device is present on STF
3. Delete WDA -> device is disconnected status on STF -> Connect device->WDA is installed and present on STF
4. Disconnect device->Delete WDA -> Connect device-> WDA is installed and present on STF
5. ./sudo reboot now - > Trust/not trust field  is not appears - > device is present on STF
6. Disconnect device -> /tools/- add incorrect WDA - Connect device -> Trust/not trust field  is not appears ->ERROR! Unable to install WebDriverAgent.ipa
```
- {"err":"your app is not properly signed for this device, check your codesigning and provisioningprofile. original error: 'ApplicationVerificationFailed' errorDescription:'Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.QyFxbE/extracted/Payload/WebDriverAgentRunner-Runner.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)'","level":"fatal","msg":"failed writing","time":"2023-08-08T10:42:35Z"}
ERROR! Unable to install WebDriverAgent.ipa!
```
