### ISSUE TITLE
upload/finish on trap is broken

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#180]
after redesign we can't detect existing ffmpeg process to share recorded content.
applicable for the iOS and Android. repro on esg execution - redroid

**Comment by vdelendik** [comment]
fixed. to test we have to confirm that:
1. video and session log artifacts present on redroid
2. video and session log artifacts present on mcloud
3. artifacts for aborted session on redroid and mcloud present

**Comment by dhreben** [comment]
Video, session log and artifacts present on mcloud
Also, actifacts present on aborted session  on mcloud as well.

Video, session log and artifacts also present on 11 redroid,also artifacts present on aborted session
