### ISSUE TITLE
for the unauthorized android device do exit with code 0

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#190]
there is no sense to restart appium container if device state is unauthorized (somebody cleaned trusted keys on device?!)
for that case let's do exit 0 to avoid permanent restart.

on this line we should exit with error code 1: https://github.com/zebrunner/appium/blob/a1c129b15da7d14cf2b24d3b35140b8f61ba2e4d/local_connect.sh#L78

**Comment by vdelendik** [comment]
let's review how it works using existing code for upcoming 2.0

**Comment by dhreben** [comment]
Verified.
```
error: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.
Not documented device state: ''. One more attempt in 5 seconds.
Restarting...
Doing usbreset forcibly on attached device
Resetting USB device /dev/bus/usb/001/021
```
