### ISSUE TITLE
Review go ios action and reuse udid

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#207]
So far ios device connected via linux is fully isolated and we could skip —udid=value option

let’s inspect all cmd and forcibly reuse udid option. Devices connected via Mac OS are visible 

also inspect stf and mcloud-device accordingly

**Comment by vdelendik** [comment]
fixed. basic acceptance should be enough for android and ios jobs

**Comment by dhreben** [comment]
Verified.
