### ISSUE TITLE
parametrize usbmuxd option for ios

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#208]
in case of Linux we have to start our own isolated usbmuxd service. But for the case when appium is used on MacOS we have to bind via socat.
I.e. on the MacOS we start proxying:
```
 socat TCP-LISTEN:2222,reuseaddr,fork UNIX-CONNECT:/var/run/usbmuxd
```

and in `local_connect.sh` instead of starting new usbmuxd just connect via socat into the shared one:
```
socat UNIX-LISTEN:/var/run/usbmuxd,fork,reuseaddr,mode=777 TCP:192.168.88.156:2222 &
```

it might be achieved by extra env var:
`USBMUXD_SOCKET_ADDRESS=value`

if empty -> start new, if declared -> bind via socat

**Comment by vdelendik** [comment]
done. sanity check for android and ios should be enough

**Comment by dhreben** [comment]
Verified.
