### ISSUE TITLE
remove pairDevice logic at all rom appium container

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#218]
Due to the https://github.com/zebrunner/mcloud-agent/issues/206 we can't share anymore on latest Mac Ventura `/private/var/db/lockdown` into the container and as result we can't control inside appium if device is pared or not...

to have the same approach on both Linux and macOS platforms it would be great to unify approaches.
Based on preliminary testing pairDevice is not obligatory at all if we do trust 1st time manually for both platforms.

it includes cased with iOS devices reconnect and reboot as well.

So let's remove completely logic about plist file detection and pairDevice call

The only disadvantage as of now is that appium container will constantly restarting until human pair it clicking onto the Trust.
and also STF container exited with 0 for the setup time (maybe separate improvement should be submitted for mcloud-device as well

**Comment by vdelendik** [comment]
done. changes are available in `apium:2.0.2`

**Comment by dhreben** [comment]
Verified.
