### ISSUE TITLE
support wireless and local connect better

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#221]
1. local connect proceed in regular way assuming device is available automatically
2. wireless device (using wi-fi network) require in advance adb connect (make sure to start adb with `-a` in advance!
3. Redroid (mix of local and wireless?)

make sure it doesn't affect esg scalable executors

**Comment by dhreben** [comment]
Reopened

**Steps:**

1.  Open Develop mode on android device - e.g Samsung_Tab_A7
2. Switch ON debugging by Wifi
3. ` docker exec -ti device-Samsung_Tab_A7-R......WX2J-appium bash`
4.  `root@74f7d224be98:/home/androidusr# ps -ef `
- Verify that  `adb -a -P 5037 server nodaemon` is up

`root    11   1 0 Sep01 pts/0  00:00:17 adb -a -P 5037 server nodaemon`
5. Switch OFF debugging by USB

**Actual result:**   Android device is not available on STF with Exited(0)  appium docker container status

**Comment by vdelendik** [comment]
@dhreben if you want to use device remotely you have to configure device according to your step and instead of udid provide device ip. this ip should be in the same network as a server where containers up and running. According to the logs you continue to refer with udid `R...WX2J` which is wrong for such use-case. 
Also `wireless: true` field should be registered for the device in main.yml

**Comment by dhreben** [comment]
Verified on prod

Opened relevant ticket https://github.com/zebrunner/appium/issues/250
