### ISSUE TITLE
Investigate if ffmpeg might capture stf output

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#235]
To be able to move recording outside and don’t concatenate big files due to the 180s limitation of screenrecord let’s try to connect to stf websocket and capture video.

if possible we can establish 2 processes in parallel and compare later the quality (pay attention to 30-60min to see if difference exists at the end)

**Comment by vdelendik** [comment]
in this case we can start recording asap as only device is occupied by start usage. Moreover, this functionality make happen recording for the manual usage as well.

**Comment by azarouski** [comment]
done `public.ecr.aws/zebrunner/appium:2.1.0-beta6`
