### ISSUE TITLE
override grid-register to make `registerToGrid(regRequest, configHolder)` at once

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#237]
there is no sense to ping every 5 sec selenium grid... in case of any problem with grid we can't execute any tests anyway.
based on our observation too often verification of the grid state lead to `hub down or disconnect`, reconnection and removing the existing session from the grid

**Comment by vdelendik** [comment]
done. changes are available in `appium:2.0.4-beta1`

**Comment by dhreben** [comment]
Basic acceptance successfully completed
