### ISSUE TITLE
Support wireless connection with real Android devices

### ISSUE THREAD

**Issue by dhreben** [zebrunner/appium#250]
An approach with port 5555 was tested in this ticket https://github.com/zebrunner/appium/issues/221.  As far as I understand, a Wifi network has been created with a static port 5555.
Let's investigate possibility how we can connect to an android device using the dynamic port  when wireless debugging is activated in development mode.
e.g.192.168.88.152:41001

**Comment by vdelendik** [comment]
it is already supported from v2.0.3: #221 and #160 
already used on the prod so closing as invalid
