### ISSUE TITLE
Devices are not available after restart mcloud-grid

### ISSUE THREAD

**Issue by dhreben** [zebrunner/appium#274]
**Steps**

1. Restart mcloud-grid
2. Open https://d.......................m/mcloud/grid/console

**Actual result:**  Devices are not available after restart mcloud-grid

Existing nodes are not loaded by the mcloud-grid. We need to restart all devices in order for nodes to be registered

**Comment by vdelendik** [comment]
new appium deployed on demo stf. we restored original grid-register.js but increased register cycle interval to 10m.
i.e. after restarting mcloud-grid devices will be reconnected in 10 minutes only. so huge interval organized as too often calls overload selenium grid.

**Comment by dhreben** [comment]
fixed
