### ISSUE TITLE
port latest recorder fixes into the appium

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#278]
we should port all latest fixes from https://github.com/zebrunner/recorder/releases to be in sync with uploader:3.4

that's existing kill: https://github.com/zebrunner/appium/blob/2aaf8df1cafcbe5621a534ed80be85e8432fcfca/entrypoint.sh#L27

**Comment by dhreben** [comment]
Verified on appium:2.0.7
Videos, screenshots and sessions are available on iOS Safari Sample, iOS Preferences Sample and Mobile Sample (Android) tests
