### ISSUE TITLE
adjust diff files porting changes

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#296]
I've made changes directly in js files: https://github.com/zebrunner/appium/pull/294
@SergeiZagriychuk, please review, refactor if needed and apply changes for the diff as well

**Comment by vdelendik** [comment]
@SergeiZagriychuk, could you please review and confirm that diffs adjusted correctly. As I remember you redesigned this functionality using standard approach

**Comment by SergeiZagriychuk** [comment]
@vdelendik exactly. this feature has been re-factored in https://github.com/zebrunner/appium/pull/304
ignoring of 400 errors from app server (added in your change) was removed

**Comment by dhreben** [comment]
Basic acceptance  with iOS-Preferences-Test ,Mobile-iOS-Safari-Test ,  Android-Demo-Test  successfully completed. Video, screenshots and logs are available.
