### ISSUE TITLE
move device type detection outside of appium

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#310]
there is no sense to define device type via the cli for android and ios. it has sense to move it outside onto the ansible level with ability to override by human via main.yml

that should simplify support of simulators/emulators and some rare android TV devices where adb return invalid type aka `default`

**Comment by vdelendik** [comment]
also let's sync about splitting wda/adb and move it outside of the appium. For iOS it is much simpler...

**Comment by azarouski** [comment]
done #374

**Comment by dhreben** [comment]
Basic acceptance with iOS-Preferences-Test ,Mobile-iOS-Safari-Test , Android-Demo-Test successfully completed. Video, screenshots and logs are available.
