### ISSUE TITLE
do exit 0 for `Device setup is not yet complete`

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#318]
Below is the example of the state when device was upgraded. For iOS tablets extra steps to unlock and setup touch id/passoptions required.
Let's move into the Unhealty state in stf and doe exit 0 from appium

```
Driver initialization 'default' FAILED! Retry 2 of 3 time - Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: Error Domain=FBSOpenApplicationErrorDomain Code=6 "Device setup is not yet complete." UserInfo={BSErrorCodeDescription=Busy, NSLocalizedFailureReason=Device setup is not yet complete.} Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.[[[--udid 54...73 --name iPad_mini_4 --sessionId 3328347f-15d4-47f0-ac22-eed2bdf864b3]]]
```

**Comment by vavadikb** [comment]
ticket was resolved in pull request https://github.com/zebrunner/appium/pull/338 

need test

**Comment by dhreben** [comment]
It was tested on 2 phones Iphone 8 and iPhone 8 Plus  ( 16.7.5.version)
After the devices were updated to the latest versions, the Appium container is up and running.  The device appeared in STF.  The setup did without any issues with setup password disabled.
iPad will be test on prod
