### ISSUE TITLE
Appium with xvfb not starting on macOs devices

### ISSUE THREAD

**Issue by azarouski** [zebrunner/appium#353]
Appium can't start together with `xvfb` on MacOs device.
https://github.com/zebrunner/appium/blob/f989b1b84d71c8e2b61f8d114703fdeaf405283d/entrypoint.sh#L17

Without `xvfb` appium is starting normally.

**Comment by azarouski** [comment]
You can test this changes on `appium:2.0.15-beta2` image

**Comment by dhreben** [comment]
Tested withappium:2.0.15-beta2
Basic acceptance with iOS-Preferences-Test ,Mobile-iOS-Safari-Test , Android-Demo-Test successfully completed. Video, screenshots and logs are available.
