### ISSUE TITLE
integrate semaphore file creation removal on session start/finish 

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#377]
1. find place in appium sources where ` session created successfully, session ` message is generated (base-driver?)
old logic which used it to determine startedSessionId is here: https://github.com/zebrunner/appium/blob/f87be734127ed7741b4b91700ca6b9124bbde048/entrypoint.sh#L227

2. inject file creation `$LOG_DIR/.recording-artifact` with such content on this step:
```
sessionId=<session-uuid>
```

3. find place in appum sources where session is finished (TBD if we can support negative scenarios as well)
example: https://github.com/zebrunner/appium/blob/f87be734127ed7741b4b91700ca6b9124bbde048/entrypoint.sh#L259
4. inject `$LOG_DIR/.recording-artifact` file removal on above step

**Comment by dhreben** [comment]
Basic acceptance successfully completed. Video, screenshots and logs are available.
