### ISSUE TITLE
do not move device into the unhealthy state for `The session identified by`

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#398]
```
The session identified by 8b661108-ba73-40f7-a65d-a98db7a862ed is not known[[[--udid 132...51 --name N...1 --sessionId d7d231bb-6220-45b8-989a-8ad8d38c227a]]]
```

above error means that something wrong with current session but it doesn't block new tests executin. I.e. no sense to move device in STF into the Unhelthy state.

@vavadikb, please remove such update in our adjusted appium sources

**Comment by vdelendik** [comment]
same for the
```
An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up[[[--udid G8S....M --name Am...10 --sessionId fc2e5b9e-e38c-4150-a873-f9ac29c1c063]]]
```

also, @vavadikb, let's remove this appendix from the updated notes everywhere: `[[[--udid G8S....M --name Am...10 --sessionId fc2e5b9e-e38c-4150-a873-f9ac29c1c063]]]` as we already assign this message to this particular device.

So ideally both these errors should be assiged into the notes without moving device into the Unheathy state.

**Comment by vavadikb** [comment]
updated in this pr https://github.com/zebrunner/appium/pull/399/files

**Comment by vavadikb** [comment]
Ticket was resolved in pull request https://github.com/zebrunner/appium/pull/399/files


Testing steps:

- build appium from this fix public.ecr.aws/zebrunner/appium:2.1.4
- you need to fill the free space on device by downloading any big files for example big csv/apk or during screen recording

it should return an error 'no space left on device'  and change status of device to Unhealthy in SFT with added in note error
