### ISSUE TITLE
webview context is not accessible

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#419]
we install latest and sometimes not compatible uiautomator2 especially for all kind of hot fix releases...
```
RUN appium driver install uiautomator2 && \
```

as result webview related mobile functionality might be broken.

**Comment by vdelendik** [comment]
fixed. changes are in `public.ecr.aws/zebrunner/appium:2.1.7-beta3`.
@dhreben, let's discuss howto test

**Comment by dhreben** [comment]
Verified on one of the production env
