### ISSUE TITLE
add recovery support for wda started as external service

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#426]
as of now we do exit 0 in appium when wda healthcheck is unsuccessful. For wda started via xcodebuild it happens pretty often that wda can't be started fast enough and appium is exited without recovery.
let's temporary add exit 1 to restart appium

**Comment by vdelendik** [comment]
done, appium:2.1.8 is pushed to the ECR. Also retagged and repushed 2.1

**Comment by dhreben** [comment]
Verified on prod
