### ISSUE TITLE
restore sharing device udid/name as part of exception for negative cases

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#45]
To continue support device detection in carina for negative cases we have to patch error messaging:
```
# PATCH #2 <appium>/node_modules/appium/node_modules/appium-base-driver/build/lib/protocol/protocol.js to return to carina "DEBUG info" about problematic step
# after 303 line add one more to update err.message
#       let actualErr = err;
#      err.message = `[[[DEBUG info: ${err.message} --udid ${process.env.DEVICE_UDID} --name ${process.env.STF_PROVIDER_DEVICE_NAME}]]]`;
```

Details: https://github.com/zebrunner/mcloud-appium/blob/9998fb50dfb0f846451d0a13eb2e4ed561debd80/Dockerfile#L65
P.S. also investigate possibility to provide fallback driver sessionId in additions

**Comment by vdelendik** [comment]
1. restored old behavior with sharing device udid and name via stacktrace exception.
2. updated a little bit format of the error:
```
[[[DEBUG info: ${err.message} --udid ${process.env.DEVICE_UDID} --name ${process.env.STF_PROVIDER_DEVICE_NAME}]]]
->
${err.message}[[[--udid ${process.env.DEVICE_UDID} --name ${process.env.STF_PROVIDER_DEVICE_NAME} --sessionId=${sessionId}]]]
```
3. added sharing in additions fallback sessionId

To test I can recommend to lock device with pin and launch android tests
-> tests failed, exception contains device name, udid and sessionId according to the pattern above
testing might be done with 7.2.14+ carina

**Comment by dhreben** [comment]
Reopened

**Comment by vdelendik** [comment]
fixed. appium:1.0 republished to ECR

**Comment by dhreben** [comment]
Verified.
