### ISSUE TITLE
sync video recording scripts to be as much close as possible to mcloud-ios desktop

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#50]
ideally patched appium scripts should work inside docker container and on mac OS itself. related ticket is https://github.com/zebrunner/mcloud-ios/issues/88

**Comment by vdelendik** [comment]
done. appium:1.1-beta1 built for testing.
to certify it on android we have to setup mcloud-agent from develop and test
-> video recording should be workable

**Comment by dhreben** [comment]
Verified.
