### ISSUE TITLE
line 5: ${PLATFORM_NAME,,}: bad substitution

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#53]
as in Mac OS default bash is 3.2 only we can't use converting to lowercase via:
```
if [[ "${PLATFORM_NAME,,}" == "ios" ]]; then
   echo captureIOSArtifacts
else
   echo not ios
fi
->
line 5: ${PLATFORM_NAME,,}: bad substitution
```

such functionality appeared only in bash 4.0
https://stackoverflow.com/questions/47815637/getting-bad-substitution-error-with-a-shell-script-on-a-mac

**Comment by vdelendik** [comment]
fixed. to test we have to deliver 1.1-beta1 appium and adjust mcloud-agent in develop branch. so sync with @vdelendik in advance to make sure infra is ready

**Comment by dhreben** [comment]
Verified.
