### ISSUE TITLE
improve healthcheck adding restart logic inside for wda

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#57]
instead of killing node/appium/wda and exit we can try to restart wda

**Comment by vdelendik** [comment]
added also wda kill. let's experiment to see if `--session-override` should be provided as well... it was discovered that single request with multiply wda tries to start app also several times

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/appium/pull/64/files
to verify we can do manual `ios kill  $WDA_BUNDLEID --udid=$DEVICE_UDID` and analyze healthcheck logs
-> in ~30 seconds after kill new WDA session should be started. to see healthcheck logs use:
```
docker inspect --format "{{json .State.Health }}" device-iPhone_XR-<udid>-appium | jq
```

**Comment by dhreben** [comment]
Verified.

![Screenshot 2022-03-17 at 14 35 58](https://user-images.githubusercontent.com/50950954/158800430-77d7f528-1dd4-4787-b1ae-a1db184a2660.png)

**Comment by vdelendik** [comment]
reopened as in 1.4 we decided to remove wda restart from healthcheck. if we can proceed without wda restart we can cancel #65

**Comment by vdelendik** [comment]
restored again wda restart on healthcheck reusing separated `/opt/start-wda.sh` script

**Comment by vdelendik** [comment]
verified successfully
