### ISSUE TITLE
start stf services only when 1st WDA session was successfully registered

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#67]
we have to improve wda stratup verification. just starting is not enough. we have to verify that 1st springboard session was successfully started.
potentially it might be part of `appium` repo

**Comment by vdelendik** [comment]
done. on exit and before start we forcibly remove WDA_ENV which is shared to stf container and block stf startup.
WDA_ENV is generated only when 1st wda session is ok.

to test verify on startup and during restart using old iPhone8 where wda session startup is low (~1min).
while 1st wda session is starting stf services waits...

**Comment by dhreben** [comment]
Verified with old iphone 6s

**Comment by vdelendik** [comment]
issue still repro

**Comment by dhreben** [comment]
Fixed
