### ISSUE TITLE
too many org.openqa.selenium.NoSuchSessionException

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#81]
during app startup UIAutomator2 might crash:
```
2022-04-12 22:01:53:634 [Instrumentation] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
2022-04-12 22:01:53:639 [Instrumentation] INSTRUMENTATION_CODE: 0
2022-04-12 22:01:53:793 [Instrumentation] The process has exited with code 0
2022-04-12 22:01:55:128 [Instrumentation] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:
```

as result this particular device crash whole run having:
```
org.openqa.selenium.WebDriverException: org.openqa.selenium.NoSuchSessionException: The session identified by 52fca685-2df1-4bbc-8a29-aa722abf5f2c is not known[[[--udid R5...PV --name Galaxy_A30 --sessionId b839c398-369f-42e9-8310-3c10c405550e]]]
```

to return device and appium into the normal state we have to uninstall  `io.appium.uiautomator2.server.test.AppiumUiAutomator2Server`

**Comment by vdelendik** [comment]
we lost such functionality after migrating from mcloud-appium: https://github.com/zebrunner/mcloud-appium/pull/32/files#diff-99eefcba174cdf7998a37489b54b1b5e676d726ed2a150b061432e9e0ff8d3abR13
```
# uninstall appium specific
adb uninstall io.appium.uiautomator2.server.test
adb uninstall io.appium.uiautomator2.server
adb uninstall io.appium.settings
adb uninstall io.appium.unlock
```

**Comment by vdelendik** [comment]
done. we returned uninstall for above 4 applications. to test please do device restart and analyze that all 4 apps are removed (in appium container logs and via device UI).
Also #82 submitted for better fix. changes should be available in `public.ecr.aws/zebrunner/appium:1.4-beta1`

**Comment by dhreben** [comment]
Verified on  4 Android UI devices.
Also checked appium logs.
