### ISSUE TITLE
capture UiAutomator2 crash asap and restart appium container

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#82]
in scope of #81 we returned cleanup on restart. At the same time to fix problem automatically we have to analyze on failure exception and forcibly exit from container with "-1" status code so next restart will uninstall problematic app

**Comment by vdelendik** [comment]
let's monitor in appium 2.0

**Comment by vdelendik** [comment]
@vavadikb, please try to reuse stf api to make device unhealthy

**Comment by vdelendik** [comment]
it shoud be fixed by https://github.com/zebrunner/appium/pull/386/files#diff-d7839b928c1c681dd6c213ca3ad4daf129cd12d82f059cd02e87a13cfeea94dfR496

testing scenario can be found in #288

**Comment by dhreben** [comment]
Verified
