### ISSUE TITLE
ios: define exit strategy from container on exit

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#87]
after kill/crash of the appium we have to verify device state and exit 0 if device is not available anymore or exit 1 to init restart on-failure.

And for testing we have to kill appium process in appium container and see stf mcloud-device
-> in ~30s it should be restarted if attempts still exists or exited

**Comment by vdelendik** [comment]
done. we do `ios list | grep $DEVICE_UDID` to define if iOS connected and visible on the start and exit.
if on exit device is not visible then appium should exit with code 0, i.e. without restart on failure

**Comment by dhreben** [comment]
Verified
